### ISSUE TITLE
Websocket refuses to transmit data. [BadResource: Bad resource ID](?)

### ISSUE THREAD

**Issue by jcc10** [jcc10/oak_websoket_middleware#1]
The websocket refuses to transmit data. It also errors out with  
```
BadResource: Bad resource ID
    at unwrapResponse (rt/10_dispatch_json.js:24:13)
    at sendSync (rt/10_dispatch_json.js:51:12)
    at close (rt/11_resources.js:16:5)
    at Conn.close (rt/30_net.js:87:7)
    at WebSocketImpl.ensureSocketClosed (mod.ts:372:17)
    at WebSocketImpl.[Symbol.asyncIterator] (mod.ts:229:14)
    at async Echo_Server.handler (echo_server.ts:15:26)
    at async WebSocketMiddleware.handler (echo_server.ts:33:43)
```  
which may or may not be related.

The error originates to the following line: ```for await (const event of ws) {``` which leads me to believe that the error is coming from the socket's event loop.

**Comment by MarkTiedemann** [comment]
@jcc10 I think this issue may be closed now since https://github.com/denoland/deno/issues/8271 is closed. Glad I was able to help. :)

**Comment by jcc10** [comment]
Yp. Thank you.
